pool:
  vmImage: "windows-latest"
variables:
  - group: test-configuration
  - name: CustomerTransferClientCertFileName
    value: CustomerTransferQA.pfx
  - name: OnlineApiClientCertFileName
    value: CarmaxOnlineArrWWWQA.pfx
  - name: ClientCertListFileName
    value: client-cert-list.json
  - name: Web_Vehicle_Service_Api_Key
    value: "$(web-vehicle-api-Key)"

stages:
- stage: PostmanCollectionTests
  displayName: "Postman Tests"
  jobs:
  - job: RunTests
    displayName: "Run Postman Tests"
    steps:
    - task: DownloadSecureFile@1
      inputs:
        secureFile: $(ClientCertListFileName)
    - task: DownloadSecureFile@1
      inputs:
        secureFile: $(CustomerTransferClientCertFileName)
    - task: DownloadSecureFile@1
      inputs:
        secureFile: $(OnlineApiClientCertFileName)

    - script: "npm install -g newman"
      displayName: "Install Newman"

    - script: "newman run https://api.getpostman.com/collections/14649430-46d35820-7eb8-4cf0-8922-5b0c864492ac?apikey=PMAK-61a800b62712ae00400b0240-9670bb076f213e0579a8d2dee913cf0bfb --bail -e Environment.json --reporters cli,junit --reporter-junit-export Results/junitReport.xml --ssl-client-cert-list D://a//_temp//$(ClientCertListFilename) --env-var web-vehicle-api-key=$(Web_Vehicle_Service_Api_Key)"
      displayName: "Run Postman Collection"

    - task: publishTestResults@2
      displayName: "Publish Test Results"
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: "**/*.xml"
        searchFolder: "Results"
        testRunTitle: "Newman Regression Tests"
